### PR TITLE
radicle-surf: fix history path filter for empty path

### PR DESCRIPTION
**Pull request by keepsimple1**
This is to solve issue #103 .

To add a new test case for this, I created a new `empty-branch` with an empty commit for [`git-platinum` repo](https://github.com/radicle-dev/git-platinum/tree/empty-branch). And also added a script to update `git-platinum` data (.tgz file) in `radicle-surf`.  The script is ported from the [original `radicle-surf`](https://github.com/radicle-dev/radicle-surf/blob/master/scripts/update-git-platinum.sh) repo. 

Also, fix the CI linter to use Rust `1.66.1` for now because the new Rust `1.67.0` triggers many lint errors. We can have a separate PR to move the code to Rust `1.67.0`.

### CODE REVIEW

**Comment by xphoniex** [comment]
why are you pushing to your own fork? aren't you a member of radicle-dev?

**Comment by keepsimple1** [comment]
> why are you pushing to your own fork? aren't you a member of radicle-dev?

Earlier on, I didn't have permissions to push directly to this repo. Now I'm already used to push to my fork for a PR. I can try to push directly in future. Is that a blocker?

**Comment by xphoniex** [comment]
> > why are you pushing to your own fork? aren't you a member of radicle-dev?
> 
> Earlier on, I didn't have permissions to push directly to this repo. Now I'm already used to push to my fork for a PR. I can try to push directly in future. Is that a blocker?

Yes, I'd appreciate if you push directly on `radicle-dev`. Thank you.

**Review by xphoniex — APPROVED** [review]
nice work, fixes the issue, lgtm!

**Comment by keepsimple1** [comment]
> Yes, I'd appreciate if you push directly on `radicle-dev`. Thank you.

Will do in the next PR. Thanks for your review!

**Pull request merged**
